openapi: 3.0.1
info:
  title: Moreu API
  description: This is a moreu server.
  contact:
    name: More Support
    url: https://saltbo.cn
    email: saltbo@foxmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: "1.0"
servers:
- url: //localhost:8080/moreu/api
paths:
  /tokens:
    post:
      tags:
      - Tokens
      summary: 登录/密码重置
      description: 用于账户登录和申请密码重置
      requestBody:
        description: 参数
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/bind.BodyToken'
        required: true
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/httputil.JSONResponse'
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/httputil.JSONResponse'
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/httputil.JSONResponse'
      x-codegen-request-body-name: body
    delete:
      tags:
      - Tokens
      summary: 退出登录
      description: 用户状态登出
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/httputil.JSONResponse'
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/httputil.JSONResponse'
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/httputil.JSONResponse'
  /user:
    get:
      tags:
      - Users
      summary: 当前登录用户信息
      description: 获取已登录用户的详细信息
      parameters:
      - name: username
        in: path
        description: 用户名
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200'
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/httputil.JSONResponse'
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/httputil.JSONResponse'
  /users:
    get:
      tags:
      - Users
      summary: 用户列表
      description: 获取用户列表信息
      parameters:
      - name: limit
        in: query
        required: false
        style: form
        explode: true
        schema:
          type: integer
      - name: name
        in: query
        required: false
        style: form
        explode: true
        schema:
          type: string
      - name: offset
        in: query
        required: false
        style: form
        explode: true
        schema:
          type: integer
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200_1'
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/httputil.JSONResponse'
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/httputil.JSONResponse'
    post:
      tags:
      - Users
      summary: 用户注册
      description: 注册一个用户
      requestBody:
        description: 参数
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/bind.BodyUser'
        required: true
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200_2'
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/httputil.JSONResponse'
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/httputil.JSONResponse'
      x-codegen-request-body-name: body
  /users/{email}:
    patch:
      tags:
      - Users
      summary: 更新一项用户信息
      description: 用于账户激活和密码重置
      parameters:
      - name: email
        in: path
        description: 邮箱
        required: true
        style: simple
        explode: false
        schema:
          type: string
      requestBody:
        description: 参数
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/bind.BodyUserPatch'
        required: true
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/httputil.JSONResponse'
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/httputil.JSONResponse'
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/httputil.JSONResponse'
      x-codegen-request-body-name: body
  /users/{username}:
    get:
      tags:
      - Users
      summary: 用户查询
      description: 获取一个用户的公开信息
      parameters:
      - name: username
        in: path
        description: 用户名
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200'
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/httputil.JSONResponse'
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/httputil.JSONResponse'
    put:
      tags:
      - Users
      summary: 修改个人信息
      description: 更新用户的个人信息
      parameters:
      - name: username
        in: path
        description: 用户名
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/httputil.JSONResponse'
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/httputil.JSONResponse'
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/httputil.JSONResponse'
components:
  schemas:
    bind.BodyToken:
      required:
      - email
      - password
      type: object
      properties:
        captcha:
          type: string
        email:
          type: string
        password:
          type: string
    bind.BodyUser:
      required:
      - email
      - password
      type: object
      properties:
        email:
          type: string
        password:
          type: string
        ticket:
          type: string
    bind.BodyUserPatch:
      required:
      - token
      type: object
      properties:
        activated:
          type: boolean
        password:
          type: string
        token:
          type: string
    bind.QueryUser:
      type: object
      properties:
        limit:
          type: integer
        name:
          type: string
        offset:
          type: integer
    gin.H:
      type: object
    httputil.JSONResponse:
      type: object
      properties:
        code:
          type: integer
        data:
          type: object
          properties: {}
          example: {}
        msg:
          type: string
      example:
        msg: msg
        code: 0
        data: {}
    model.User:
      type: object
      properties:
        activated:
          type: boolean
        created:
          type: string
        email:
          type: string
        id:
          type: integer
        role:
          type: string
        ticket:
          type: string
        updated:
          type: string
        username:
          type: string
        ux:
          type: string
          description: Global unique user ID
      example:
        role: role
        ux: ux
        ticket: ticket
        created: created
        id: 0
        updated: updated
        email: email
        activated: true
        username: username
    model.UserFormats:
      type: object
      properties:
        avatar:
          type: string
        bio:
          type: string
        company:
          type: string
        created:
          type: string
        email:
          type: string
        id:
          type: integer
        location:
          type: string
        nickname:
          type: string
        role:
          type: string
        updated:
          type: string
        url:
          type: string
        username:
          type: string
        ux:
          type: string
    model.UserProfile:
      type: object
      properties:
        avatar:
          type: string
        bio:
          type: string
        company:
          type: string
        created:
          type: string
        id:
          type: integer
        location:
          type: string
        nickname:
          type: string
        updated:
          type: string
        url:
          type: string
        ux:
          type: string
      example:
        ux: ux
        created: created
        nickname: nickname
        bio: bio
        company: company
        location: location
        avatar: avatar
        id: 0
        updated: updated
        url: url
    inline_response_200:
      type: object
      properties:
        data:
          $ref: '#/components/schemas/model.UserProfile'
        httputil.JSONResponse:
          $ref: '#/components/schemas/httputil.JSONResponse'
      example:
        data:
          ux: ux
          created: created
          nickname: nickname
          bio: bio
          company: company
          location: location
          avatar: avatar
          id: 0
          updated: updated
          url: url
        httputil.JSONResponse:
          msg: msg
          code: 0
          data: {}
    inline_response_200_1:
      type: object
      properties:
        data:
          type: object
          allOf:
          - $ref: '#/components/schemas/gin.H'
          - type: object
            properties:
              list:
                type: array
                items:
                  $ref: '#/definitions/model.UserFormats'
        httputil.JSONResponse:
          $ref: '#/components/schemas/httputil.JSONResponse'
        total:
          type: integer
      example:
        total: 0
        data: ""
        httputil.JSONResponse:
          msg: msg
          code: 0
          data: {}
    inline_response_200_2:
      type: object
      properties:
        data:
          $ref: '#/components/schemas/model.User'
        httputil.JSONResponse:
          $ref: '#/components/schemas/httputil.JSONResponse'
      example:
        data:
          role: role
          ux: ux
          ticket: ticket
          created: created
          id: 0
          updated: updated
          email: email
          activated: true
          username: username
        httputil.JSONResponse:
          msg: msg
          code: 0
          data: {}
